import React from "react";

// DD-MMM-YY  e.g. 21-Aug-23
function formatDate(dateStr) {
  if (!dateStr) return "—";
  const d = new Date(dateStr);
  if (isNaN(d)) return "—";
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  const dd = String(d.getDate()).padStart(2, "0");
  const mmm = months[d.getMonth()];
  const yy = String(d.getFullYear()).slice(-2);
  return `${dd}-${mmm}-${yy}`;
}

// YYYY-MM-DD  e.g. 2023-08-21 (used for RFQ date)
function formatDateISO(dateStr) {
  if (!dateStr) return "—";
  const d = new Date(dateStr);
  if (isNaN(d)) return "—";
  const yy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yy}-${mm}-${dd}`;
}

export default function EnquiryTable({
  enquiries,
  total,
  page,
  totalPages,
  onPageChange,
  onSort,
  sortField,
  sortOrder,
  onView,
  onEdit,
  onDownload,
  limit,
}) {
  const startRecord = (page - 1) * limit + 1;
  const endRecord = Math.min(page * limit, total);

  const renderSortIcon = (field) => {
    if (sortField !== field) return null;
    return sortOrder === "asc" ? " ▲" : " ▼";
  };

  const handleSort = (field) => {
    onSort(field);
  };

  return (
    <div className="enquiry-table-wrapper">
      <div className="enquiry-table-scroll">
        <table className="enquiry-table">
          <thead>
            {/* Section headers */}
            <tr className="table-section-header">
              <th colSpan="4" className="section-bo">BO / Enquiry Details</th>
              <th colSpan="4" className="section-part">Part Number Mapping</th>
              <th colSpan="2" className="section-po">PO Number</th>
              <th colSpan="2" className="section-generated">Generated</th>
              <th colSpan="1" className="section-actions">Actions</th>
            </tr>
            {/* Column headers */}
            <tr>
              {/* BO / Enquiry */}
              <th onClick={() => handleSort("customerName")}>
                Customer Name{renderSortIcon("customerName")}
              </th>
              <th onClick={() => handleSort("customerRFQDate")}>
                Customer RFQ Date{renderSortIcon("customerRFQDate")}
              </th>
              <th>Item Description</th>
              

              {/* Part Number Mapping */}
              <th>Customer Part No</th>
            <th>BO Part Name</th>
              <th>Modified BO Part No</th>
               <th onClick={() => handleSort("enquiryNumber")}>
                Inquiry Number Generated{renderSortIcon("enquiryNumber")}
              </th>

              {/* PO */}
              <th onClick={() => handleSort("poDetails.supplierName")}>
                Supplier Name{renderSortIcon("poDetails.supplierName")}
              </th>
              <th onClick={() => handleSort("poDetails.poNumber")}>
                PO Number{renderSortIcon("poDetails.poNumber")}
              </th>
              <th>Date of Issue</th>

              {/* Generated */}
              <th onClick={() => handleSort("generatedBy")}>
                Generated By{renderSortIcon("generatedBy")}
              </th>
              <th onClick={() => handleSort("createdAt")}>
                Generated On{renderSortIcon("createdAt")}
              </th>

              {/* Actions */}
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {enquiries.length === 0 ? (
              <tr>
                <td colSpan="14" style={{ textAlign: "center", padding: "40px" }}>
                  No enquiries found
                </td>
              </tr>
            ) : (
              enquiries.map((enq) => (
                <tr key={enq._id}>
                  {/* BO / Enquiry Details */}
                  <td data-label="Customer Name">{enq.customerName || "—"}</td>
                  <td data-label="RFQ Date">{formatDateISO(enq.customerRFQDate)}</td>
                  <td data-label="Item Description">
                    {enq.itemDescription
                      ? enq.itemDescription.length > 30
                        ? enq.itemDescription.substring(0, 30) + "..."
                        : enq.itemDescription
                      : "—"}
                  </td>
            

                  {/* Part Number Mapping */}
                  <td data-label="Customer Part No">
                    {enq.partMapping?.customerPartNo || "—"}
                  </td>
                  <td data-label="BO Part Name">
                    {enq.partMapping?.boPartName
                      ? enq.partMapping.boPartName.length > 20
                        ? enq.partMapping.boPartName.substring(0, 20) + "..."
                        : enq.partMapping.boPartName
                      : "—"}
                  </td>
                   <td data-label="Modified BO Part No">
                    {enq.partMapping?.modifiedBOPartNo ? (
                      <span className="cell-bo-part">
                        {enq.partMapping.modifiedBOPartNo}
                      </span>
                    ) : (
                      "—"
                    )}
                  </td> 
                      <td data-label="Inquiry Number">
                    <span className="cell-badge">{enq.enquiryNumber || "—"}</span>
                  </td>

                  {/* PO Section */}
                  <td data-label="Supplier Name">
                    <span className="cell-supplier-link">
                      {enq.poDetails?.supplierName || "—"}
                    </span>
                  </td>
                  <td data-label="PO Number">
                    {enq.poDetails?.poNumber ? (
                      <span className="cell-po">{enq.poDetails.poNumber}</span>
                    ) : (
                      "—"
                    )}
                  </td>
                  <td data-label="Date of Issue">
                    {formatDate(enq.poDetails?.dateOfIssue)}
                  </td>

                  {/* Generated */}
                  <td data-label="Generated By">
                    <strong>{enq.generatedBy || "—"}</strong>
                  </td>
                  <td data-label="Generated On">{formatDate(enq.createdAt)}</td>

                  {/* Actions */}
                  <td data-label="Actions">
                    <div className="actions-cell">
                      <button className="action-btn view" title="View" onClick={() => onView(enq)}>
                        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
                          <circle cx="12" cy="12" r="3"/>
                        </svg>
                      </button>
                      <button className="action-btn edit" title="Edit" onClick={() => onEdit(enq)}>
                        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/>
                          <path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/>
                        </svg>
                      </button>
                      <button className="action-btn download" title="Download" onClick={() => onDownload(enq)}>
                        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
                          <polyline points="7 10 12 15 17 10"/>
                          <line x1="12" y1="15" x2="12" y2="3"/>
                        </svg>
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      <div className="enquiry-pagination">
        <div className="pagination-info">
          Showing <strong>{startRecord}-{endRecord}</strong> of{" "}
          <strong>{total}</strong> records
        </div>
        <div className="pagination-buttons">
          <button
            className="pagination-btn"
            disabled={page <= 1}
            onClick={() => onPageChange(page - 1)}
          >
            Previous
          </button>
          <button
            className="pagination-btn"
            disabled={page >= totalPages}
            onClick={() => onPageChange(page + 1)}
          >
            Next
          </button>
        </div>
      </div>
    </div>
  );
}
