import React from "react";

export default function EnquiryFilters({
  filters,
  onFilterChange,
  filterOptions,
}) {
  const handleChange = (field, value) => {
    onFilterChange({ ...filters, [field]: value });
  };

  return (
    <div className="enquiry-filters">
      <div className="filters-header">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M22 3H2l8 9.46V19l4 2v-8.54L22 3z" />
        </svg>
        Advanced Filters
      </div>

      <div className="filters-grid">
        <div className="filter-field">
          <label>Customer Name</label>
          <select
            value={filters.customerName || ""}
            onChange={(e) => handleChange("customerName", e.target.value)}
          >
            <option value="">All Customers</option>
            {(filterOptions.customers || []).map((c) => (
              <option key={c} value={c}>{c}</option>
            ))}
          </select>
        </div>

        <div className="filter-field">
          <label>Supplier Name</label>
          <select
            value={filters.supplierName || ""}
            onChange={(e) => handleChange("supplierName", e.target.value)}
          >
            <option value="">All Suppliers</option>
            {(filterOptions.suppliers || []).map((s) => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
        </div>

        <div className="filter-field">
          <label>RFQ Date From</label>
          <input
            type="date"
            value={filters.rfqDateFrom || ""}
            onChange={(e) => handleChange("rfqDateFrom", e.target.value)}
          />
        </div>

        <div className="filter-field">
          <label>RFQ Date To</label>
          <input
            type="date"
            value={filters.rfqDateTo || ""}
            onChange={(e) => handleChange("rfqDateTo", e.target.value)}
          />
        </div>

        <div className="filter-field">
          <label>Inquiry Number</label>
          <input
            type="text"
            placeholder="Search inquiry..."
            value={filters.inquiryNumber || ""}
            onChange={(e) => handleChange("inquiryNumber", e.target.value)}
          />
        </div>

        <div className="filter-field">
          <label>PO Number</label>
          <input
            type="text"
            placeholder="Search PO..."
            value={filters.poNumber || ""}
            onChange={(e) => handleChange("poNumber", e.target.value)}
          />
        </div>

        <div className="filter-field">
          <label>Part Number</label>
          <input
            type="text"
            placeholder="Search part..."
            value={filters.partNumber || ""}
            onChange={(e) => handleChange("partNumber", e.target.value)}
          />
        </div>

        <div className="filter-field">
          <label>Generated By</label>
          <select
            value={filters.generatedBy || ""}
            onChange={(e) => handleChange("generatedBy", e.target.value)}
          >
            <option value="">All Users</option>
            {(filterOptions.generatedByList || []).map((g) => (
              <option key={g} value={g}>{g}</option>
            ))}
          </select>
        </div>
      </div>

      <div className="global-search-field">
        <span className="global-search-icon">🔍</span>
        <input
          type="text"
          placeholder="Global search across all fields..."
          value={filters.search || ""}
          onChange={(e) => handleChange("search", e.target.value)}
        />
      </div>
    </div>
  );
}
